// Generated by CoffeeScript 1.11.0
(function() {
  'use strict';
  var Collection, Model, View, View2;

  Model = Backbone.Model.extend({
    initialize: function() {}
  });

  Collection = Backbone.Collection.extend({
    initialize: function() {},
    findByFigureId: function(id) {
      return this.find(function(figure) {
        return figure.get('figure_id') === id;
      });
    }
  });

  View2 = Backbone.View.extend({
    initialize: function() {},
    update: function(model) {
      console.log(model);
      console.log(model.toJSON());
      return console.log(JSON.stringify(model));
    }
  });

  View = Backbone.View.extend({
    el: "body",
    initialize: function() {
      var collection, json, model, view2;
      json = {
        'figure_id': 111,
        'name': 'naoki'
      };
      model = new Model(json);
      collection = new Collection([model]);
      view2 = new View2({
        model: model
      });
      view2.update(model);
      return view2.render();
    }
  });

  new View();

}).call(this);
